name: static_anaysis

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:
  schedule:
    - cron: "1 * * * *"
      timezone: 'Asia/Kuala_Lumpur'

jobs:
  static_anaysis:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: setup_php
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'

      - name: "copy env"
        run: cp .env.example .env

      - name: "generate app key"
        run: php artisan key:generate
        
      - name: "install dependacies"
        run: composer install

      - name: "install phpstan"
        run: composer require --dev phpstan/phpstan

      - name: run static code analysis
        run:  vendor/bin/phpstan analyse -l 6 app
